import java.util.Scanner;

public class Lottery {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//Participation Question
		//Have a random two digit number generated by system. (10-99)
		//Guess a two digit number.
		//If both #s same, $1000 reward
		//If in reverse, $500 reward
		//One # same, $100 reward
		//Else, print "Sorry. Play again."
		//Please do integer comparisons.
		
		int l1 = (int)(10 + 89 * Math.random());
		Scanner inp = new Scanner(System.in);

		System.out.println("Please enter two digit number: ");
		
		int l2 = inp.nextInt();

		while (l2 < 10 || l2 >99) {
			System.out.println("Invalid, Please enter two digit number again: ");
			l2 = inp.nextInt();
		}
		
		System.out.println("The lucky number is: " + l1);
		
		int l1n1 = (int)(l1 / 10);
		int l1n2 = (int)(l1 % 10);
		int l2n1 = (int)(l2 / 10);
		int l2n2 = (int)(l2 % 10);
		
		if (l1 == l2)
			System.out.println("Jackpot! You win $1000");
		else if (l1n1 == l2n2 && l1n2 == l2n1)
			System.out.println("You win $500");
		else if (l1n1 == l2n1 || l1n2 == l2n1 || l1n1 == l2n2 || l1n2 == l2n2)
			System.out.println("You win $100");
		else
			System.out.println("Sorry. Play again.");
		}

	}

